### ISSUE TITLE
Unexpected AttributeError when deleting Proxy

### ISSUE THREAD

**Issue by SamSchott** [irmen/Pyro5#17]
In rare cases, an unexpected error is raised when a Proxy instance gets deleted / garbage collected:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Pyro5/client.py", line 80, in __del__
AttributeError: 'NoneType' object has no attribute 'suppress'
```
The relevant line in `Pyro4.client.Proxy` is:

```python
with contextlib.suppress(Exception):
    self._pyroRelease()
```
This issue has been introduced with 217af7b11b6a4f7231bbe88df2bd197d35ca839a and  seems to only occur when exiting the interpreter.

**Comment by irmen** [comment]
Hmm, these kind of obscure errors make me think that implementing ``__del__`` is maybe not worth the hassle.....    On the other hand I'd really like Pyro to free resources it doesn't need anymore when a proxy gets destroyed...

In my experience, this particular type of error indeed only occurs when the whole interpreter is shutting down. I don't really like sprinkling all sorts of extra attribute / None checks in the del method, but maybe that's the only way to prevent these kind of errors from leaking out

**Comment by SamSchott** [comment]
Yes, I fully understand. And it’s a very rare issue.

A possible alternative to implementing ˋ__del__ˋ with proper checks and exception handling may be to provide a context manager, i.e., ˋ__enter__ˋ and ˋ__exit__ˋ methods. But it would only be practical if the Proxy is only used temporarily.

This is actually how I am using Pyro Proxies myself at the moment.

**Comment by irmen** [comment]
Those context manager methods are already present.

**Comment by SamSchott** [comment]
Right, somehow I had overlooked that.

**Comment by Daniel-Chin** [comment]
I just encountered a similar behavior using 2750a3aef20f0b530b39deb3918915acb5084dad  

In my case, the warning is thrown at  
https://github.com/irmen/Pyro5/blob/2750a3aef20f0b530b39deb3918915acb5084dad/Pyro5/socketutil.py#L440  
where `contextlib` suddenly evaluates to `None`. Usually this happens at interpreter exit:  
```
Exception ignored in: <function SocketConnection.__del__ at 0x7fd569cef6a0>
Traceback (most recent call last):
  File "/home/.../.venv/lib/python3.12/site-packages/Pyro5/socketutil.py", line 423, in __del__
  File "/home/.../.venv/lib/python3.12/site-packages/Pyro5/socketutil.py", line 440, in close
AttributeError: 'NoneType' object has no attribute 'suppress'
```

While messing with gc ordering, I found that if you manually pop the pyro modules from `sys.modules` before the interpreter exits, then the warning will NOT be raised:  
```python
    for x in [*sys.modules]:
        if 'pyro' in x.lower():
            sys.modules.pop(x)
```

I even failed to make a minimum project reproducing this. If necessary, I can attach a link to my downstream project where this consistently happens.

What could have caused `contextlib` to become `None`?

**Comment by Daniel-Chin** [comment]
Just adding some thoughts since I'm encountering this issue extensively:  
1. use `atexit.register` instead of `__del__`?  
2. Add a pyro-package-wide (singleton) context manager? On exit it releases everything.

1 is probably more modern-python but requires more work. 2 should be easy? Just gc everything known to pyro.

Update:  
In my case this simple cleanup works:  
```python
def releasePyro():
    keyword = 'Pyro5'
    sys.modules.pop(keyword)    # this asserts package name (in case Pyro6)
    for module_name in sys.modules.copy():
        if module_name.startswith(keyword):
            sys.modules.pop(module_name, None)
```
